# Use the official Node.js image from the Docker registry
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

RUN npm install -g nodemon

# Copy package.json and package-lock.json
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port 5000
EXPOSE 5000

# Run the application in development mode
CMD ["npm", "run", "dev"]