version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ecommerce
    volumes:
      - node-mysql-data:/var/lib/mysql
    networks:
      - node-mysql-network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  node:
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    image: nilaypophalkar/node-js-sample-node
    container_name: node-app
    environment:
      - DB=ecommerce
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - host=mysql
    networks:
      - node-mysql-network
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

volumes:
  node-mysql-data:
    # external: true
    
networks:
  node-mysql-network:
    # external: true