version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    volumes:
      - node-mysql-data:/var/lib/mysql
    networks:
      - node-mysql-network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: node-app
    environment:
      DB: ecommerce
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: mysql
    networks:
      - node-mysql-network
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      # Type: bind mount for code in the root directory
      - .:/app
      # Type: volume for node_modules persistence in the container
      - node_modules:/app/node_modules
    command: npm run dev # Runs development-specific scripts
    restart: always

volumes:
  node-mysql-data:
  node_modules:  # Defining volume for node_modules to persist it independently

networks:
  node-mysql-network:
